version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      args:
        SET_USER: ${SET_USER}
    environment:
      AWS_ACCESS_KEY_ID: ${SET_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SET_AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${SET_AWS_DEFAULT_REGION}
      AWS_DEFAULT_OUTPUT: ${SET_AWS_DEFAULT_OUTPUT_FORMAT}
      TZ: ${TIME_ZONE}
    privileged: true
    tty: true
#    links:
#      - db
    volumes:
      - ./real_data/httpd/log:/var/log/httpd
      - ./server:/var/www/html
    ports:
      - 80:80
      - 443:443


#  db:
#    image: mysql:latest
#    environment:
#      - MYSQL_ROOT_PASSWORD: root
#      - MYSQL_DATABASE: docker-database
#      - MYSQL_USER: docker
#      - MYSQL_PASSWORD: docker
#      - TZ: 'Asia/Tokyo'
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - ./docker/db/data:/var/lib/mysql
#      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
#      - ./docker/db/sql:/docker-entrypoint-initdb.d
#    ports:
#      - 3306:3306



#version: "3"
#services:
#  web:
#    build:
#      context: ./apache-php
#    ports: 
#      - 80:80
#    privileged: true
#    links:
#      - db
#    volumes:
#      - "./lara-d/:/var/www/html"
#      - "./apache-php/apache.conf:/etc/httpd/conf/httpd.conf"
#    container_name: "apache-php"
#  db:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#    container_name: "mysql5.7"
