version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      args:
        SET_USER: ${SET_USER}
    environment:
      AWS_ACCESS_KEY_ID: ${SET_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SET_AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${SET_AWS_DEFAULT_REGION}
      AWS_DEFAULT_OUTPUT: ${SET_AWS_DEFAULT_OUTPUT_FORMAT}
      TZ: ${TIME_ZONE}
    privileged: true
    tty: true
    links:
      - db
    volumes:
      - ./real_data/httpd/log:/var/log/httpd
      - ./server:/var/www/html
    ports:
      - 80:80
      - 443:443
  db:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${SET_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SET_MYSQL_DATABASE}
      MYSQL_USER: ${SET_MYSQL_USER}
      MYSQL_PASSWORD: ${SET_MYSQL_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./real_data/db/log:/var/log/mysql
    ports:
      - 3306:3306
volumes:
  mysql_data:
